version: '3.7'

services:
  async:
    container_name: async
    restart: always
    build:
      context: ./code/async
      dockerfile: Dockerfile
    environment:
      - ENV=production
      - PORT=8080
    ports:
      - "8080:8080"
  app:
    depends_on:
      - async
    container_name: app
    restart: always
    build:
      context: ./code/app
      dockerfile: Dockerfile
    environment:
      VITE_ASYNC_HOST: http://async:8080
    ports:
      - "80:3000"
