version: '3.7'

services:
  mysql:
    container_name: mysql
    build:
      context: ./code/database/
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - "./db_data:/var/lib/mysql"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 160

  async:
    depends_on:
      mysql:
        condition: service_healthy
    container_name: async
    restart: always
    build:
      context: ./code/async
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    secrets:
      - game_cert 
      - game_priv
        
  django:
    depends_on:
      mysql:
        condition: service_healthy
    container_name: django
    restart: always
    build:
      context: ./code/django
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    secrets:
      - api_cert
      - api_priv

  app:
    container_name: app
    restart: always
    build:
      context: ./code/app
      dockerfile: Dockerfile
    env_file: ./env/app.env
    ports:
      - "3000:3000"

secrets:
  game_cert:
    file: /etc/ssl/www/certificate.crt
  game_priv:
    file: /etc/ssl/www/private.key
  api_cert:
    file: /etc/ssl/www/certificate.crt
  api_priv:
    file: /etc/ssl/www/private.key

networks:
  default:
    name: chessverse
