version: '3.7'

services:
  mysql:
    container_name: mysql
    build:
      context: ./code/database/
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - "./db_data:/var/lib/mysql"
    command: --wait_timeout=999999
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 160

  async:
    depends_on:
      mysql:
        condition: service_healthy
    container_name: async
    restart: always
    build:
      context: ./code/async
      dockerfile: Dockerfile
    environment:
      - ENV=production
      - PORT=8080
      - DATABASE_NAME=users_db
      - DATABASE_HOST=mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
    ports:
      - "8080:8080"
    secrets:
      - ssl_certificate.crt
      - ssl_priv_key.key
        
  django:
    depends_on:
      mysql:
        condition: service_healthy
    container_name: django
    restart: always
    build:
      context: ./code/django
      dockerfile: Dockerfile
    environment:
      - ENV=production
      - PORT=8000
      - DATABASE_NAME=users_db
      - DATABASE_HOST=mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
    ports:
      - "8000:8000"
    secrets:
      - ssl_certificate.crt
      - ssl_priv_key.key

  app:
    container_name: app
    restart: always
    build:
      context: ./code/app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

secrets:
  ssl_certificate.crt:
    file: /etc/ssl/certificate.crt
  ssl_priv_key.key:
    file: /etc/ssl/private/private.key

networks:
  default:
    name: chessverse
