version: '3.7'

services:
  mysql:
    container_name: mysql
    build:
      context: ../code/database/
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 160
    volumes:
       - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - cas-network
networks:
  cas-network:
    external: true